// ─── Runtime environment configuration ───────────────────────────────────────
// Priority: window.__ENV__ (injected at container start) → import.meta.env (dev)
//
// In production (Docker / Cloud Run) the values come from env-config.js, which
// is generated by docker-entrypoint.sh reading the Cloud Run env vars at boot.
// In local development Vite injects VITE_* from .env.local as usual.

interface RuntimeEnv {
  VITE_AUTH_BASE_URL?: string;
  VITE_SEARCH_BASE_URL?: string;
  VITE_BOOKING_BASE_URL?: string;
  VITE_ENV_NAME?: string;
}

declare global {
  interface Window {
    __ENV__?: RuntimeEnv;
  }
}

function runtimeVar(key: keyof RuntimeEnv): string {
  return window.__ENV__?.[key] ?? (import.meta.env[key] as string | undefined) ?? '';
}

export const AUTH_BASE_URL   = runtimeVar('VITE_AUTH_BASE_URL');
export const SEARCH_BASE_URL = runtimeVar('VITE_SEARCH_BASE_URL');
export const BOOKING_BASE_URL = runtimeVar('VITE_SEARCH_BASE_URL');
export const ENV_NAME        = runtimeVar('VITE_ENV_NAME');
